export type EventStateTypes =
	| "JOB_ACCEPTED"
	| "WORKER_STARTED"
	| "ATTEMPT_CREATED"
	| "SENDING_REQUEST"
	| "WAITING_FOR_RESPONSE"
	| "RESPONSE_GET"
	| "RESPONSE_VALIDATED"
	| "COMPLETE"
	| "RECOVERY_STARTED"
	| "RECOVERY_ABANDONED"
	| "RECOVERY_COMPLETE"
	| "FAILED";
